# Generated by Django 3.1.2 on 2020-12-30 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feux',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('green', models.SmallIntegerField(default=0)),
                ('orange', models.SmallIntegerField(default=0)),
                ('red', models.SmallIntegerField(default=0)),
                ('green_duration', models.IntegerField(default=10)),
                ('orange_duration', models.IntegerField(default=7)),
                ('red_duration', models.IntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='Voie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('NORTH', 'NORTH'), ('SOUTH', 'SOUTH'), ('WEST', 'WEST'), ('EAST', 'EAST')], max_length=10)),
                ('nombre_voiture', models.IntegerField(default=0)),
                ('feux', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electro.feux')),
            ],
        ),
    ]
